<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Do People Try To Self Repair?? | Booklike Summary of E-Waste Work</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Do People Try To Self Repair?? | Booklike Summary of E-Waste Work" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Do People Try To Self Repair?? | Booklike Summary of E-Waste Work" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Rayhan Rashed" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="method.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">E-Waste Quant Study Workbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Do People Miss Their Device??</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Can We Dig Further??</a></li>
<li class="chapter" data-level="3" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>3</b> Do People Try To Self Repair??</a></li>
<li class="chapter" data-level="4" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>4</b> Can we go beyond simple predictors?</a></li>
<li class="chapter" data-level="5" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>5</b> Applications</a><ul>
<li class="chapter" data-level="5.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>6</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Booklike Summary of E-Waste Work</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="literature" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Do People Try To Self Repair??</h1>
<pre><code>## Warning: package &#39;DiagrammeR&#39; was built under R version 4.0.1</code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.0.1</code></pre>
<pre><code>## 
## Call:
## glm(formula = repair_try ~ age + gender + edu + device_count_5_yr + 
##     miss_dev + dump_reason_new + dump_reason_old + dump_reason_break + 
##     dump_reason_theft + dump_reason_slow + dump_reason_lag + 
##     slt_lack_tu + slt_lack_lang + slt_lack_notint + slt_lack_fear + 
##     slt_lack_parts + slt_lack_repairer + rprd_usage_chlng_No + 
##     rprd_usage_chlng_reluc + rprd_usage_chlng_dur + rprd_usage_chlng_fault + 
##     rpr_missing_trait_behave + rpr_missing_trait_ineff + rpr_missing_trait_harm + 
##     rpr_missing_trait_hard + rpr_missing_trait_wage + rpr_missing_trait_trust + 
##     rpr_missing_trait_gender + bad_rep_exp + dev_tknto_rec_Y + 
##     dev_rec_chlng_fair_price + dev_rec_chlng_usable + dev_rec_chlng_datasec + 
##     dev_rec_chlng_env_poll + dev_rec_chlng_hard_find + will_dev_rec + 
##     did_with_data_Y + did_with_device_econ, family = binomial, 
##     data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5975  -0.8572   0.4249   0.7828   1.9465  
## 
## Coefficients:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                -3.81453  176.55050  -0.022 0.982762    
## age1                        3.44412  176.55067   0.020 0.984436    
## age2                        2.41671  176.54929   0.014 0.989078    
## age3                        3.32647  176.54948   0.019 0.984967    
## age4                        3.15159  176.55392   0.018 0.985758    
## genderWoman                -0.76601    0.33177  -2.309 0.020952 *  
## eduBachelors               -0.45058    0.32919  -1.369 0.171072    
## eduMasters                 -1.07114    0.55062  -1.945 0.051733 .  
## device_count_5_yr           0.11875    0.06172   1.924 0.054337 .  
## miss_dev1                   0.27342    0.29558   0.925 0.354952    
## dump_reason_new1            0.07219    0.37264   0.194 0.846401    
## dump_reason_old1           -0.42721    0.36414  -1.173 0.240712    
## dump_reason_break1         -0.57940    0.34560  -1.676 0.093644 .  
## dump_reason_theft1         -0.04497    0.55333  -0.081 0.935222    
## dump_reason_slow1          -0.25820    0.47821  -0.540 0.589242    
## dump_reason_lag1            0.22845    0.34634   0.660 0.509502    
## slt_lack_tu1                0.85707    0.33681   2.545 0.010937 *  
## slt_lack_lang1              0.74359    0.39371   1.889 0.058936 .  
## slt_lack_notint1           -0.31912    0.35723  -0.893 0.371688    
## slt_lack_fear1             -0.32464    0.30748  -1.056 0.291053    
## slt_lack_parts1             0.70065    0.30417   2.304 0.021251 *  
## slt_lack_repairer1          0.72305    0.33431   2.163 0.030556 *  
## rprd_usage_chlng_No1        0.09627    0.47985   0.201 0.840985    
## rprd_usage_chlng_reluc1    -0.24016    0.34020  -0.706 0.480238    
## rprd_usage_chlng_dur1       0.19056    0.36570   0.521 0.602310    
## rprd_usage_chlng_fault1    -0.70492    0.36279  -1.943 0.052012 .  
## rpr_missing_trait_behave1  -0.07719    0.40245  -0.192 0.847906    
## rpr_missing_trait_ineff1   -0.25274    0.30859  -0.819 0.412776    
## rpr_missing_trait_harm1    -0.19489    0.30877  -0.631 0.527936    
## rpr_missing_trait_hard1     0.41141    0.31345   1.313 0.189349    
## rpr_missing_trait_wage1     0.16748    0.29675   0.564 0.572492    
## rpr_missing_trait_trust1    0.65292    0.31573   2.068 0.038646 *  
## rpr_missing_trait_gender1   0.80964    0.49728   1.628 0.103495    
## bad_rep_expN               -0.15473    0.41822  -0.370 0.711399    
## bad_rep_expY                0.33971    0.39820   0.853 0.393596    
## dev_tknto_rec_Y1            0.60860    0.32634   1.865 0.062194 .  
## dev_rec_chlng_fair_price1   0.09209    0.28958   0.318 0.750469    
## dev_rec_chlng_usable1      -0.18539    0.30092  -0.616 0.537841    
## dev_rec_chlng_datasec1      0.21768    0.32591   0.668 0.504180    
## dev_rec_chlng_env_poll1     0.19792    0.32119   0.616 0.537756    
## dev_rec_chlng_hard_find1   -1.14618    0.45119  -2.540 0.011075 *  
## will_dev_recN               0.02867    0.36626   0.078 0.937615    
## will_dev_recY              -0.35005    0.46936  -0.746 0.455780    
## did_with_data_Y1            0.28373    0.30745   0.923 0.356089    
## did_with_device_econ1       1.31402    0.37878   3.469 0.000522 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 448.21  on 350  degrees of freedom
## Residual deviance: 346.64  on 306  degrees of freedom
## AIC: 436.64
## 
## Number of Fisher Scoring iterations: 13</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">backward.model &lt;-<span class="st"> </span><span class="kw">step</span>(full.model,<span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>,<span class="dt">trace =</span> <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"></a>
<a class="sourceLine" id="cb4-3" data-line-number="3">backward.model <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = repair_try ~ gender + device_count_5_yr + dump_reason_break + 
##     slt_lack_tu + slt_lack_lang + slt_lack_parts + slt_lack_repairer + 
##     rprd_usage_chlng_fault + rpr_missing_trait_trust + rpr_missing_trait_gender + 
##     dev_tknto_rec_Y + dev_rec_chlng_hard_find + did_with_device_econ, 
##     family = binomial, data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4999  -0.9607   0.5115   0.8135   1.7348  
## 
## Coefficients:
##                           Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)               -1.25724    0.48891  -2.572  0.01013 * 
## genderWoman               -0.76450    0.29607  -2.582  0.00982 **
## device_count_5_yr          0.11214    0.05442   2.061  0.03932 * 
## dump_reason_break1        -0.40389    0.26534  -1.522  0.12796   
## slt_lack_tu1               0.90456    0.30414   2.974  0.00294 **
## slt_lack_lang1             0.75308    0.37256   2.021  0.04324 * 
## slt_lack_parts1            0.73106    0.27123   2.695  0.00703 **
## slt_lack_repairer1         0.68465    0.30933   2.213  0.02688 * 
## rprd_usage_chlng_fault1   -0.66105    0.29823  -2.217  0.02665 * 
## rpr_missing_trait_trust1   0.64316    0.27960   2.300  0.02143 * 
## rpr_missing_trait_gender1  0.70075    0.45174   1.551  0.12085   
## dev_tknto_rec_Y1           0.53534    0.28816   1.858  0.06320 . 
## dev_rec_chlng_hard_find1  -1.03492    0.39741  -2.604  0.00921 **
## did_with_device_econ1      1.01172    0.32764   3.088  0.00202 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 448.21  on 350  degrees of freedom
## Residual deviance: 367.01  on 337  degrees of freedom
## AIC: 395.01
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><span class="math display">\[
\begin{aligned}
\log\left[ \frac { P( repair\_try = 1 ) }{ 1 - P( repair\_try = 1 ) } \right] &amp;= -1.26 - 0.76(gender_{woman}) + 0.11(device\_count\_5\_yr)\ - \\
&amp;\quad 0.4(dump\_reason\_break) + 0.9(lack\_of\_tutorial) + 0.75(language\_barrier\_of\_tutorial)\ + \\
&amp;\quad 0.73(lack\_of\_parts) + 0.68(lack\_of\_good\_repairer) - 0.66(fear_that_repaired_device_faulty)\ + \\
&amp;\quad 0.64(repairers\_lack\_trust) + 0.7(gender\_adversary\_of\_repairers) + 0.54(dev\_tknto\_rec\_Y)\ - \\
&amp;\quad 1.03(dev\_rec\_chlng\_hard\_find) + 1.01(did\_with\_device\_econ_{1}) + \epsilon
\end{aligned}
\]</span>
The AIC Value was Initially 436.
After Stepwise Regression, it came down to 395.</p>
<p>The 10 fold cross validation accuracy is below:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">cross_validated_model &lt;-<span class="st"> </span>boot<span class="op">::</span><span class="kw">cv.glm</span>(df,<span class="dt">glmfit =</span> backward.model,<span class="dt">K =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="kw">print</span>((<span class="dv">1</span><span class="op">-</span>cross_validated_model<span class="op">$</span>delta[<span class="dv">1</span>])<span class="op">*</span><span class="dv">100</span>)</a></code></pre></div>
<pre><code>## [1] 80.77318</code></pre>
<p>Lets also look at the ROC curve for the the fitted logistic regression model:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">null.model &lt;-<span class="st"> </span><span class="kw">glm</span>(repair_try<span class="op">~</span><span class="dv">1</span>,<span class="dt">family =</span> <span class="kw">binomial</span>(),<span class="dt">data =</span> df)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="kw">Generate_RoC</span>(<span class="dt">full_model =</span> full.model,<span class="dt">null_model =</span> null.model,<span class="dt">df =</span> df,<span class="dt">direction =</span> <span class="st">&quot;B&quot;</span>,<span class="dt">outcome =</span> <span class="st">&quot;repair_try&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 351</code></pre>
<pre><code>## Setting levels: control = 0, case = 1</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<p><img src="Book_files/figure-html/unnamed-chunk-5-1.png" width="672" />
With a good fit in the model, lets diagnosis our model parameters for multicolineariy. If the <strong><em>VIF</em></strong> (Variance Inflation Factor) is <span class="math inline">\(&gt;10\)</span> for any predictor, we might be in trouble.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MIN IVF: &quot;</span>,<span class="kw">min</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MIN IVF:  1.034216</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MAX IVF: &quot;</span>,<span class="kw">max</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MAX IVF:  1.242712</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MEAN IVF: &quot;</span>,<span class="kw">mean</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MEAN IVF:  1.124022</code></pre>
<p>Values <span class="math inline">\(&gt;0\)</span> means odd&gt;1 So, that accounts more for YES than NO.</p>
<p><strong><em>gender_woman: </em></strong> <span class="math inline">\(-0.76\)</span>:
Typicaly women are less inclined toward repair.</p>
<p><strong><em>device_count_5_yr: </em></strong> <span class="math inline">\(0.11\)</span> The more number of devices you have had during the last 5 years, the more you are inclined to try repair your own devices.</p>
<p><strong><em>lack_of_tutorial</em></strong>: <span class="math inline">\(0.9\)</span> If you feel that there is lack of tutorial out there, then there is a solid chance that you at least tried repair your own, but probably did/not succeed due to the lack of it.</p>
<p><strong><em>language_barrier_of_tutorial</em></strong>: <span class="math inline">\(0.75\)</span> This also predicts very well you feel that there is lack of tutorial <strong><em>In Your Own Language</em></strong>, but for the same reason stated above, there is solid chance that you at least tried repair your own, giving odd ratio of <span class="math inline">\(2.12\)</span>.</p>
<p><strong><em>lack_of_parts</em></strong>: <span class="math inline">\(0.73\)</span> Similar reason.</p>
<p><strong><em>fear that trying to repair will lead to faulty device</em></strong> <span class="math inline">\(−0.66\)</span> The negative log odd says this fear will lead to less amount of self repair trial.</p>
<p><strong><em>repairers_lack_trust: </em></strong> <span class="math inline">\(0.64\)</span> When you dont trust the repairers out there in the market, you try to do it on your own.</p>
<p><strong><em>gender_adversary_of_repairers: </em></strong> <span class="math inline">\(0.70\)</span> Gender Adversary makes you more likely to try your own luck. )</p>
<p><strong><em>device ever taken to RECYCLER: </em></strong> <span class="math inline">\(0.54\)</span> If you know the recycler community, and used to give them your devices/sell to them, then you care less about the safety and usefulness, and overcome fear to try your own.</p>
<p><strong><em>Hard to Find RECYCLER: </em></strong> $ -1.03$ The above effect is better described with understanding from this. When you find it hard to find any recycler, your fear of losing the device utility (log odd -0.66) intensifies. And, so you do not try repair your devices on your own.</p>
<p><strong><em>Have you did anything economic with your device? (selling/parts selling etc) </em></strong> <span class="math inline">\(1.01\)</span>. If you know your device still has some monetary value, you try to do your own. [Probably a bit contradictory! How do we fix that ? :P]</p>
<p>Lets look at the effects plot to better understand the individual effects of each predictor:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="co">#librarian::shelf(effects)</span></a>
<a class="sourceLine" id="cb18-2" data-line-number="2"></a>
<a class="sourceLine" id="cb18-3" data-line-number="3"><span class="cf">for</span> (n <span class="cf">in</span> <span class="kw">c</span>(</a>
<a class="sourceLine" id="cb18-4" data-line-number="4"><span class="st">&quot;gender&quot;</span></a>
<a class="sourceLine" id="cb18-5" data-line-number="5">,<span class="st">&quot;did_with_device_econ&quot;</span></a>
<a class="sourceLine" id="cb18-6" data-line-number="6">,<span class="st">&quot;device_count_5_yr&quot;</span></a>
<a class="sourceLine" id="cb18-7" data-line-number="7">,<span class="st">&quot;dump_reason_break&quot;</span></a>
<a class="sourceLine" id="cb18-8" data-line-number="8">,<span class="st">&quot;slt_lack_tu&quot;</span></a>
<a class="sourceLine" id="cb18-9" data-line-number="9">,<span class="st">&quot;slt_lack_lang&quot;</span></a>
<a class="sourceLine" id="cb18-10" data-line-number="10">,<span class="st">&quot;slt_lack_parts&quot;</span></a>
<a class="sourceLine" id="cb18-11" data-line-number="11">,<span class="st">&quot;slt_lack_repairer&quot;</span></a>
<a class="sourceLine" id="cb18-12" data-line-number="12">,<span class="st">&quot;rprd_usage_chlng_fault&quot;</span></a>
<a class="sourceLine" id="cb18-13" data-line-number="13">,<span class="st">&quot;rpr_missing_trait_trust&quot;</span></a>
<a class="sourceLine" id="cb18-14" data-line-number="14">,<span class="st">&quot;rpr_missing_trait_gender&quot;</span></a>
<a class="sourceLine" id="cb18-15" data-line-number="15">,<span class="st">&quot;dev_tknto_rec_Y&quot;</span></a>
<a class="sourceLine" id="cb18-16" data-line-number="16">,<span class="st">&quot;dev_rec_chlng_hard_find&quot;</span></a>
<a class="sourceLine" id="cb18-17" data-line-number="17">)){</a>
<a class="sourceLine" id="cb18-18" data-line-number="18">  <span class="co">#print(n)</span></a>
<a class="sourceLine" id="cb18-19" data-line-number="19">  <span class="kw">print</span>(<span class="kw">plot</span>(effects<span class="op">::</span><span class="kw">predictorEffect</span>(n,backward.model)))</a>
<a class="sourceLine" id="cb18-20" data-line-number="20">}</a></code></pre></div>
<p><img src="Book_files/figure-html/unnamed-chunk-7-1.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-2.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-3.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-4.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-5.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-6.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-7.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-8.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-9.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-10.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-11.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-12.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-13.png" width="672" /></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="method.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Book.pdf", "Book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
