<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Can we go beyond simple predictors? | Booklike Summary of E-Waste Work</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Can we go beyond simple predictors? | Booklike Summary of E-Waste Work" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Can we go beyond simple predictors? | Booklike Summary of E-Waste Work" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Rayhan Rashed" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="literature.html"/>
<link rel="next" href="applications.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">E-Waste Quant Study Workbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Do People Miss Their Device??</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Can We Dig Further??</a></li>
<li class="chapter" data-level="3" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>3</b> Do People Try To Self Repair??</a></li>
<li class="chapter" data-level="4" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>4</b> Can we go beyond simple predictors?</a></li>
<li class="chapter" data-level="5" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>5</b> Applications</a><ul>
<li class="chapter" data-level="5.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>6</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Booklike Summary of E-Waste Work</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="method" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Can we go beyond simple predictors?</h1>
<pre><code>## Warning: package &#39;DiagrammeR&#39; was built under R version 4.0.1</code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.0.1</code></pre>
<p>This time we have added the following Interactions:</p>
<p>device_count_5_yr:rprd_usage_chlng_fault</p>
<p>device_count_5_yr:dev_tknto_rec_Y</p>
<p>device_count_5_yr:did_with_device_econ</p>
<p>slt_lack_tu:dev_tknto_rec_Y</p>
<p>slt_lack_lang:rpr_missing_trait_gender+slt_lack_parts:rpr_missing_trait_gender+rpr_missing_trait_gender:dev_rec_chlng_hard_find+rpr_missing_trait_trust:dev_rec_chlng_hard_find+rpr_missing_trait_gender:did_with_device_econ</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">backward.model &lt;-<span class="st"> </span><span class="kw">step</span>(full.model,<span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>,<span class="dt">trace =</span> <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"></a>
<a class="sourceLine" id="cb3-3" data-line-number="3">backward.model <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = repair_try ~ gender + device_count_5_yr + dump_reason_break + 
##     slt_lack_tu + slt_lack_lang + slt_lack_parts + slt_lack_repairer + 
##     rprd_usage_chlng_fault + rpr_missing_trait_trust + rpr_missing_trait_gender + 
##     dev_tknto_rec_Y + dev_rec_chlng_hard_find + did_with_device_econ + 
##     device_count_5_yr:rprd_usage_chlng_fault + device_count_5_yr:dev_tknto_rec_Y + 
##     slt_lack_tu:dev_tknto_rec_Y + rpr_missing_trait_gender:did_with_device_econ, 
##     family = binomial, data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4798  -0.9052   0.3998   0.7900   1.8345  
## 
## Coefficients:
##                                                Estimate Std. Error z value
## (Intercept)                                     0.08008    0.60611   0.132
## genderWoman                                    -0.76520    0.30643  -2.497
## device_count_5_yr                              -0.10481    0.08528  -1.229
## dump_reason_break1                             -0.39397    0.27349  -1.441
## slt_lack_tu1                                    0.60696    0.34801   1.744
## slt_lack_lang1                                  0.66268    0.38551   1.719
## slt_lack_parts1                                 0.82522    0.28030   2.944
## slt_lack_repairer1                              0.64544    0.31311   2.061
## rprd_usage_chlng_fault1                        -2.08754    0.63395  -3.293
## rpr_missing_trait_trust1                        0.72791    0.28796   2.528
## rpr_missing_trait_gender                       -0.55054    0.79032  -0.697
## dev_tknto_rec_Y1                               -1.44058    0.80486  -1.790
## dev_rec_chlng_hard_find1                       -1.06221    0.41026  -2.589
## did_with_device_econ1                           0.74643    0.35720   2.090
## device_count_5_yr:rprd_usage_chlng_fault1       0.28921    0.11153   2.593
## device_count_5_yr:dev_tknto_rec_Y1              0.31305    0.14984   2.089
## slt_lack_tu1:dev_tknto_rec_Y1                   1.61188    0.73681   2.188
## rpr_missing_trait_gender:did_with_device_econ1  1.68981    0.96570   1.750
##                                                Pr(&gt;|z|)    
## (Intercept)                                    0.894891    
## genderWoman                                    0.012520 *  
## device_count_5_yr                              0.219066    
## dump_reason_break1                             0.149713    
## slt_lack_tu1                                   0.081142 .  
## slt_lack_lang1                                 0.085620 .  
## slt_lack_parts1                                0.003239 ** 
## slt_lack_repairer1                             0.039267 *  
## rprd_usage_chlng_fault1                        0.000992 ***
## rpr_missing_trait_trust1                       0.011478 *  
## rpr_missing_trait_gender                       0.486053    
## dev_tknto_rec_Y1                               0.073476 .  
## dev_rec_chlng_hard_find1                       0.009622 ** 
## did_with_device_econ1                          0.036644 *  
## device_count_5_yr:rprd_usage_chlng_fault1      0.009512 ** 
## device_count_5_yr:dev_tknto_rec_Y1             0.036686 *  
## slt_lack_tu1:dev_tknto_rec_Y1                  0.028696 *  
## rpr_missing_trait_gender:did_with_device_econ1 0.080146 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 448.21  on 350  degrees of freedom
## Residual deviance: 349.44  on 333  degrees of freedom
## AIC: 385.44
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><span class="math display">\[
\begin{aligned}
\log\left[ \frac { P( repair\_try = 1 ) }{ 1 - P( repair\_try = 1 ) } \right] &amp;= 0.08 - 0.77(gender_{Woman}) - 0.1(device\_count\_5\_yr)\ - \\
&amp;\quad 0.39(dump\_reason\_break) + 0.61(slt\_lack\_tu) + 0.66(slt\_lack\_lang)\ + \\
&amp;\quad 0.83(slt\_lack\_parts) + 0.65(slt\_lack\_repairer) - 2.09(rprd\_usage\_chlng\_fault)\ + \\
&amp;\quad 0.73(rpr\_missing\_trait\_trust) - 0.55(gender_{rpr\_missing\_trait\_} \times rpr\_missing\_trait\_gender) - 1.44(dev\_tknto\_rec\_Y)\ - \\
&amp;\quad 1.06(dev\_rec\_chlng\_hard\_find) + 0.75(did\_with\_device\_econ_{1}) + 0.29(device\_count\_5\_yr \times rprd\_usage\_chlng\_fault)\ + \\
&amp;\quad 0.31(device\_count\_5\_yr \times dev\_tknto\_rec\_Y) + 1.61(slt\_lack\_tu \times dev\_tknto\_rec\_Y) + 1.69(gender_{rpr\_missing\_trait\_} \times rpr\_missing\_trait\_gender_{did\_with\_device\_econ1} \times did\_with\_device\_econ_{rpr\_missing\_trait\_gender})\ + \\
&amp;\quad \epsilon
\end{aligned}
\]</span></p>
<p>The AIC Value was Initially 436.</p>
<p>After Stepwise Regression, it came down to 395.</p>
<p><strong><em>After Adding the Interaction elements, it is now 385</em></strong></p>
<p>The 10 fold cross validation accuracy is below:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">cross_validated_model &lt;-<span class="st"> </span>boot<span class="op">::</span><span class="kw">cv.glm</span>(df,<span class="dt">glmfit =</span> backward.model,<span class="dt">K =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="kw">print</span>((<span class="dv">1</span><span class="op">-</span>cross_validated_model<span class="op">$</span>delta[<span class="dv">1</span>])<span class="op">*</span><span class="dv">100</span>)</a></code></pre></div>
<pre><code>## [1] 80.74644</code></pre>
<p>Lets also look at the ROC curve for the the fitted logistic regression model: <strong><em>(A better fit than model without interaction)</em></strong></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">null.model &lt;-<span class="st"> </span><span class="kw">glm</span>(repair_try<span class="op">~</span><span class="dv">1</span>,<span class="dt">family =</span> <span class="kw">binomial</span>(),<span class="dt">data =</span> df)</a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="kw">Generate_RoC</span>(<span class="dt">full_model =</span> full.model,<span class="dt">null_model =</span> null.model,<span class="dt">df =</span> df,<span class="dt">direction =</span> <span class="st">&quot;B&quot;</span>,<span class="dt">outcome =</span> <span class="st">&quot;repair_try&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 351</code></pre>
<pre><code>## Setting levels: control = 0, case = 1</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<p><img src="Book_files/figure-html/unnamed-chunk-5-1.png" width="672" />
With a good fit in the model, lets diagnosis our model parameters for multicolineariy. If the <strong><em>VIF</em></strong> (Variance Inflation Factor) is <span class="math inline">\(&gt;10\)</span> for any predictor, we might be in trouble.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MIN IVF: &quot;</span>,<span class="kw">min</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MIN IVF:  1.054682</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MAX IVF: &quot;</span>,<span class="kw">max</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MAX IVF:  6.98304</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">cat</span>(<span class="st">&quot;MEAN IVF: &quot;</span>,<span class="kw">mean</span>(<span class="kw">vif</span>(backward.model)))</a></code></pre></div>
<pre><code>## MEAN IVF:  2.6841</code></pre>
<p>Values <span class="math inline">\(&gt;0\)</span> means odd<span class="math inline">\(&gt;1\)</span> So, that accounts more for YES than NO.</p>
<p><strong><em>device_count_5_yr : fear of faulty device </em></strong></p>
<p><strong><em>device_count_5_yr: device ever taken to RECYCLER </em></strong></p>
<p><strong><em>lack_of_tutorial : device ever taken to RECYCLER </em></strong></p>
<p><strong><em>gender_adversary_of_repairers :Have you did anything economic with your device</em></strong></p>
<p>Lets look at the effects plot to better understand the individual effects of each predictor:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="co">#librarian::shelf(effects)</span></a>
<a class="sourceLine" id="cb17-2" data-line-number="2"></a>
<a class="sourceLine" id="cb17-3" data-line-number="3"><span class="cf">for</span> (n <span class="cf">in</span> <span class="kw">c</span>(</a>
<a class="sourceLine" id="cb17-4" data-line-number="4"><span class="st">&quot;gender&quot;</span>,</a>
<a class="sourceLine" id="cb17-5" data-line-number="5"><span class="st">&quot;device_count_5_yr&quot;</span></a>
<a class="sourceLine" id="cb17-6" data-line-number="6">,<span class="st">&quot;dump_reason_break&quot;</span></a>
<a class="sourceLine" id="cb17-7" data-line-number="7">,<span class="st">&quot;slt_lack_tu&quot;</span></a>
<a class="sourceLine" id="cb17-8" data-line-number="8">,<span class="st">&quot;slt_lack_lang&quot;</span></a>
<a class="sourceLine" id="cb17-9" data-line-number="9">,<span class="st">&quot;slt_lack_parts&quot;</span></a>
<a class="sourceLine" id="cb17-10" data-line-number="10">,<span class="st">&quot;slt_lack_repairer&quot;</span></a>
<a class="sourceLine" id="cb17-11" data-line-number="11">,<span class="st">&quot;rprd_usage_chlng_fault&quot;</span></a>
<a class="sourceLine" id="cb17-12" data-line-number="12">,<span class="st">&quot;rpr_missing_trait_trust&quot;</span></a>
<a class="sourceLine" id="cb17-13" data-line-number="13">,<span class="st">&quot;rpr_missing_trait_gender&quot;</span></a>
<a class="sourceLine" id="cb17-14" data-line-number="14">,<span class="st">&quot;dev_rec_chlng_hard_find&quot;</span>,</a>
<a class="sourceLine" id="cb17-15" data-line-number="15"><span class="st">&quot;did_with_device_econ&quot;</span></a>
<a class="sourceLine" id="cb17-16" data-line-number="16">,<span class="st">&quot;dev_tknto_rec_Y&quot;</span></a>
<a class="sourceLine" id="cb17-17" data-line-number="17">)){</a>
<a class="sourceLine" id="cb17-18" data-line-number="18">  <span class="cf">if</span>(n<span class="op">==</span><span class="st">&quot;dev_tknto_rec_Y&quot;</span>)</a>
<a class="sourceLine" id="cb17-19" data-line-number="19">  {</a>
<a class="sourceLine" id="cb17-20" data-line-number="20">    <span class="kw">print</span>(<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>)))</a>
<a class="sourceLine" id="cb17-21" data-line-number="21">    <span class="kw">print</span>(<span class="kw">plot</span>(effects<span class="op">::</span><span class="kw">predictorEffect</span>(n,backward.model),<span class="dt">lines=</span><span class="kw">list</span>(<span class="dt">multiline=</span><span class="ot">TRUE</span>)))</a>
<a class="sourceLine" id="cb17-22" data-line-number="22">      <span class="cf">break</span>()</a>
<a class="sourceLine" id="cb17-23" data-line-number="23">  }</a>
<a class="sourceLine" id="cb17-24" data-line-number="24">  <span class="co">#print(n)</span></a>
<a class="sourceLine" id="cb17-25" data-line-number="25">  <span class="kw">print</span>(<span class="kw">plot</span>(effects<span class="op">::</span><span class="kw">predictorEffect</span>(n,backward.model)))</a>
<a class="sourceLine" id="cb17-26" data-line-number="26">}</a></code></pre></div>
<p><img src="Book_files/figure-html/unnamed-chunk-7-1.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-2.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-3.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-4.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-5.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-6.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-7.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-8.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-9.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-10.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-11.png" width="672" /><img src="Book_files/figure-html/unnamed-chunk-7-12.png" width="672" /></p>
<pre><code>## $mfrow
## [1] 1 1</code></pre>
<p><img src="Book_files/figure-html/unnamed-chunk-7-13.png" width="672" /></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="literature.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Book.pdf", "Book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
